//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC_DBFillerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lap
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int DriverId { get; set; }
        public string Car { get; set; }
        public short LapNo { get; set; }
        public int Time { get; set; }
        public short Cuts { get; set; }
        public short Position { get; set; }
        public float Grip { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Session Session { get; set; }
    }
}
