//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC_DBFillerEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AC_DBEntities : DbContext
    {
        public AC_DBEntities()
            : base("name=AC_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Lap> Laps { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
    }
}
