//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC_ServiceClient.ACServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ACServiceReference.IACService")]
    public interface IACService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACService/PostResult", ReplyAction="http://tempuri.org/IACService/PostResultResponse")]
        void PostResult(AC_SessionReport.SessionReport report);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IACServiceChannel : AC_ServiceClient.ACServiceReference.IACService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACServiceClient : System.ServiceModel.ClientBase<AC_ServiceClient.ACServiceReference.IACService>, AC_ServiceClient.ACServiceReference.IACService {
        
        public ACServiceClient() {
        }
        
        public ACServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PostResult(AC_SessionReport.SessionReport report) {
            base.Channel.PostResult(report);
        }
    }
}
